VandVCLubManagementSystem/Controllers/MemberController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic;
using VandVCLubManagementSystem.Models;
using VandVCLubManagementSystem.Models.ViewModels.Member;
using VandVCLubManagementSystem.Persistence;
using Index = VandVCLubManagementSystem.Models.ViewModels.Member.Index;

namespace VandVCLubManagementSystem.Controllers
{
    public class MemberController : Controller
    {

        private readonly IMemberRepository _repository;
        private readonly IMapper _mapper;

        public MemberController(IMemberRepository repository, IMapper mapper)
        {
            _repository = repository;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {

            var query = _repository.GetMembers();
            var members = await query.Take(10).ToListAsync();
            var options = new Collection()
            {
                new {Id = 1, Description = "Latest Members"},
                new {Id = 2, Description = "Oldest Members"},
                new {Id = 3, Description = "Name Ascending"},
                new {Id = 4, Description = "Name Descending"},
            };
            var m = new Index()
            {
                OrderOptions = new SelectList(options, "Id", "Description"),
                TotalPages = query.Count() / 10 + 1,
                People = members,
                PageNumber = 1
            };
            return View(m);
        }


        [HttpPost]
        public async Task<IActionResult> Index(Index m)
        {

            var query = _repository.GetMembers(m);

            List<Person> members;
            switch (m.OrderOptionId)
            {
                case 2:
                    members = await query.OrderBy(p => p.Id).Skip((m.PageNumber.Value - 1) * 10).Take(10).ToListAsync();
                    break;
                case 3:
                    members = await query.OrderBy(p => p.FirstName).Skip((m.PageNumber.Value - 1) * 10).Take(10).ToListAsync();
                    break;
                case 4:
                    members = await query.OrderByDescending(p => p.FirstName).Skip((m.PageNumber.Value - 1) * 10).Take(10).ToListAsync();
                    break;
                default:
                    members = await query.OrderByDescending(p => p.Id).Skip((m.PageNumber.Value - 1) * 10).Take(10).ToListAsync();
                    break;
            }

            var options = new Collection()
            {
                new {Id = 1, Description = "Latest Members"},
                new {Id = 2, Description = "Oldest Members"},
                new {Id = 3, Description = "Name Ascending"},
                new {Id = 4, Description = "Name Descending"},
            };

            m.OrderOptions = new SelectList(options, "Id", "Description");
            m.TotalPages = query.Count() / 10 + 1;
            m.People = members;

            return View(m);
        }


        public IActionResult Create()
        {
            var m = new Create();
            return View(m);
        }


        [HttpPost]
        public async Task<IActionResult> Create(Create m)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var member = _mapper.Map<Person>(m);
                    await _repository.Add(member);
                    return RedirectToAction(nameof(Confirmation), new { id = member.Id });
                }
                catch (Exception)
                {
                    ModelState.AddModelError("Exception", "Something went wrong!!");
                }
            }
            return View(m);
        }

        public async Task<IActionResult> Confirmation(int id)
        {

            var member = await _repository.GetMember(id);
            if (member == null) return NotFound();
            var m = _mapper.Map<Create>(member);
            return View(m);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var member = await _repository.GetMember(id);
            if (member == null)
            {
                return NotFound();
            }
            var m = _mapper.Map<Edit>(member);
            return View(m);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(Edit m)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    await _repository.EditMember(m);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception)
                {
                    ModelState.AddModelError("Exception", "Something went wrong!!");
                }
            }
            return View(m);
        }


        public async Task<IActionResult> DeleteConfirmation(int id)
        {
            var member = await _repository.GetMember(id);
            if (member == null)
            {
                return NotFound();
            }
            var m = _mapper.Map<Edit>(member);
            return View(m);
        }


        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var member = await _repository.GetMember(id);
                if (member == null)
                {
                    return NotFound();
                }
                await _repository.Remove(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                ModelState.AddModelError("Exception", "Something went wrong!!");
            }
            return RedirectToAction(nameof(DeleteConfirmation), new { id });
        }


    }
}

VandVCLubManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VandVCLubManagementSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="mb-0">
    <div class="container-fluid">
        <div class="row flex-nowrap">
            <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
                <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                        <span class="fs-5 d-none d-sm-inline">V&V Club</span>
                    </a>
                    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link align-middle px-0">
                                <i class="fs-4"></i> <span class="ms-1 d-none d-sm-inline">Home </span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6zm5-.793V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"></path>
                                    <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"></path>
                                </svg>
                            </a>
                        </li>
                        <li>
                            <ul class="collapse show nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
                                <li class="w-100">
                                    <a asp-area="" asp-controller="Member" asp-action="Index" class="nav-link px-0">
                                        <span class="d-none d-sm-inline">
                                            Members
                                        </span>
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                                            <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"></path>
                                            <path fill-rule="evenodd" d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z"></path>
                                            <path d="M4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z"></path>
                                        </svg>
                                    </a>
                                </li>
                                <li>
                                    <a asp-area="" asp-controller="Member" asp-action="Create" class="nav-link px-0">
                                        <span class="d-none d-sm-inline">
                                            New Member
                                        </span>
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus-fill" viewBox="0 0 16 16">
                                            <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"></path>
                                            <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"></path>
                                        </svg>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Home" asp-action="Help" class="nav-link px-0 align-middle">
                                <i class="fs-4"></i> <span class="ms-1 d-none d-sm-inline">Help </span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                                    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM5.496 6.033h.825c.138 0 .248-.113.266-.25.09-.656.54-1.134 1.342-1.134.686 0 1.314.343 1.314 1.168 0 .635-.374.927-.965 1.371-.673.489-1.206 1.06-1.168 1.987l.003.217a.25.25 0 0 0 .25.246h.811a.25.25 0 0 0 .25-.25v-.105c0-.718.273-.927 1.01-1.486.609-.463 1.244-.977 1.244-2.056 0-1.511-1.276-2.241-2.673-2.241-1.267 0-2.655.59-2.75 2.286a.237.237 0 0 0 .241.247zm2.325 6.443c.61 0 1.029-.394 1.029-.927 0-.552-.42-.94-1.029-.94-.584 0-1.009.388-1.009.94 0 .533.425.927 1.01.927z"></path>
                                </svg>
                            </a>
                        </li>
                    </ul>
                    <hr>
                </div>
            </div>
            <div class="col pb-0 m-4">
                <main role="main">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>





    @*<header>
            <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VandVCLubManagementSystem</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="Index">Members</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="Index" asp-route-membershipState="2">Non-Active Members</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>*@
    @*<div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>